
title: Luba's website
email: xle2@u.rochester.edu
description: > # this means to ignore newlines until "baseurl:"
 Luba's website. Meditation reflections + lifehacks + projects + travel notes + spill out my self
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lubalesuan

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
